# Generated by Django 3.2.9 on 2021-11-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0003_alter_station_last_cleaned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='station',
            name='last_cleaned_date',
            field=models.DateField(),
        ),
    ]
