# Generated by Django 3.2.9 on 2021-11-17 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20211117_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='schedule',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
